version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    networks:
      - what_net
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    volumes:
      - ./db_data:/app/db

networks:
  what_net:
